steps:
  # 1. Compilar la imagen usando la variable $_ENTORNO
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/repo-$_ENTORNO/mi-app:$SHORT_SHA', 
      '.'
    ]

  # 2. Subir la imagen al repositorio correspondiente
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/$PROJECT_ID/repo-$_ENTORNO/mi-app:$SHORT_SHA'
    ]

  # 3. Desplegar en Cloud Run inyectando una variable de entorno interna
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mi-app-$_ENTORNO'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/repo-$_ENTORNO/mi-app:$SHORT_SHA'
      - '--region=us-central1'
      - '--set-env-vars=ENTORNO_NAME=$_ENTORNO'
      - '--allow-unauthenticated'

substitutions:
  _ENTORNO: 'dev'

options:
  logging: CLOUD_LOGGING_ONLY
